spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:informes_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:devpruebas.zar@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:amsmnehxupkixfjx}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        messaging: DEBUG
        web.socket: DEBUG
        mail: DEBUG

jwt:
  secret: ${JWT_SECRET:clave_secreta_de_al_menos_32_caracteres}
  header: Authorization
  prefix: Bearer
  expiration-time: 86400000

app:
  security:
    super-admin-registration:
      enabled: true
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:9000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha
    docExpansion: none
    filter: true
  api-docs:
    path: /v3/api-docs